services:
  syncio:
    image: syncio:latest
    container_name: syncio
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ~/syncio/files
        target: /app/sync.io-cache
